import { globSync, readFileSync, writeFileSync } from 'node:fs';

const SCREENS = new URL('../public/screens/', import.meta.url);
const OUT = new URL('../src/styles/screenshot-sizes.css', import.meta.url);

// Screenshots are cut at twice the width they should occupy, so they stay sharp on a dense display.
// Laid out at full pixel width a tall side panel becomes a figure longer than the window, so each
// one is pinned to half its pixels: the size the crop was taken at, and the size at which the app's
// own type reads as it does in the app.
const DENSITY = 2;
const COLUMN = 672;

// Capture density cannot be read out of a PNG, so the few shots taken at 1x are named here and laid
// out at their own width. Re-shoot one at 2x and delete its line; the layout does not change, the
// picture just stops being soft.
const CAPTURED_AT_1X = new Set([
  'media/background-image-panel.png',
  'media/ambient-sound-panel.png',
  'media/background-music-panel.png',
  'media/media-conflict-panel.png',
]);

const size = (file) => {
  const header = readFileSync(new URL(file, SCREENS)).subarray(16, 24);
  return { width: header.readUInt32BE(0), height: header.readUInt32BE(4) };
};

const files = globSync('*/**/*.png', { cwd: SCREENS }).sort();

// A figure exists once per language and the two shots can differ in resolution, so the width is
// decided per figure and shared. Only the ratio is per file, because translated labels wrap
// differently and change the height.
const widths = new Map();
for (const file of files) {
  const figure = file.split('/').slice(1).join('/');
  const { width } = size(file);
  widths.set(figure, Math.max(widths.get(figure) ?? 0, width));
}

const rules = files.map((file) => {
  const figure = file.split('/').slice(1).join('/');
  const { width, height } = size(file);
  const density = CAPTURED_AT_1X.has(figure) ? 1 : DENSITY;
  const shown = Math.min(Math.round(widths.get(figure) / density), COLUMN);
  return `.sl-markdown-content img[src$='/screens/${file}'] {
  width: ${shown}px;
  aspect-ratio: ${width} / ${height};
}`;
});

writeFileSync(OUT, `/*
 * Generated by scripts/screenshot-sizes.mjs. Run \`npm run sizes\` after recropping.
 * Pins each screenshot to half its pixel width so a 2x asset lays out at its intended size,
 * and declares its ratio so the page does not jump while the image loads.
 */

${rules.join('\n\n')}
`);

console.log(`screenshot-sizes.css: ${files.length} files, ${widths.size} figures`);
